export const INCREMENT = 'INCREMENT'

export const DELETE_ARTICLE = 'DELETE_ARTICLE'

export const CHANGE_SELECTED_ARTICLES = 'CHANGE_SELECTED_ARTICLES'

export const CHANGE_DATE_INTERVAL = 'CHANGE_DATE_INTERVAL'
